### ISSUE TITLE
Mainland China detection problem。

### ISSUE THREAD

**Issue by z991238** [9seconds/mtg#92] opened 2019-07-13 09:20 UTC
GFW in mainland China seems to have begun to strengthen the detection of MTP agents. Now that some of the large IP addresses and ports are blocked, will the author have a better solution?

**Comment by troilus** [comment] 2019-07-15 23:28
blocked after one day

**Comment by 9seconds** [comment] 2019-07-16 11:44
I will try to do my best if someone will provide me with pcap files on how they do it. At this certain moment, I do not know how to help there.

Do you list these proxies publicly anywhere? Can government organizations pick these addresses from some channels or websites?

**Comment by z991238** [comment] 2019-07-16 13:54
> 如果有人会向我提供有关他们如何做的pcap文件，我会尽力做到最好。在这个特定的时刻，我不知道如何帮助那里。
> 
> 您是否在任何地方公开列出这些代理？政府组织可以从某些渠道或网站中选择这些地址吗？

I built the MTP agent only for a few people I know who are using this agent. I don't know if DPI recognition in mainland China more accurately identifies MTP agents. I have not publicly released this self-built agent to others for use in any channel.

**Comment by pexcn** [comment] 2019-07-16 14:38
same problem.

**Comment by 9seconds** [comment] 2019-07-19 18:39
@z991238 it could happen by the number of reasons: suspicious IP subnet, proxy address leakage (it always possible) and so on. I would really really like to help but do not know even how to start: the description of the problem is too broad for me so I cannot conduct any experiment or make any theory.

**Comment by z991238** [comment] 2019-07-20 12:48
> @ z991238它可能由多个原因发生：可疑的IP子网，代理地址泄漏（它总是可能的）等等。我真的很想帮忙，但不知道怎么开始：问题的描述对我来说太宽泛，所以我不能进行任何实验或做任何理论。

The IP address leak does not exist because I try to change the IP address every time after it is blocked. Subnet leaks are also impossible, if you have changed the IP subnet and IPv4 address. This situation still exists. It can only be said that the DPI of the Chinese mainland GFW has detected characteristics. It is said that this DPI situation in mainland China is more difficult for you to solve. It has been stuck for a while after the release of your 0.16 version. Recently, GFW in mainland China has begun to block the TG agent on a large scale.

**Comment by Prurite** [comment] 2019-07-21 07:45
> @z991238 it could happen by the number of reasons: suspicious IP subnet, proxy address leakage (it always possible) and so on. I would really really like to help but do not know even how to start: the description of the problem is too broad for me so I cannot conduct any experiment or make any theory.

Looks like MTProto is already detectable, a lot of proxies get blocked only after a few days ( with light traffic and not shared to public ). About the GFW - have a look at some project for bypassing the wall like https://github.com/shadowsocks/shadowsocks-windows, you'll see how strong the firewall is. An idea is make the traffic as a mess as possble ( So the firewall can't recongize it ) or mask as some usual protocols like https. Sorry for any spelling errors.

**Comment by 9seconds** [comment] 2019-07-22 10:56
Good news, everyone. It seems that TG is going to introduce yet another mechanism which will help to avoid censorship and connection is going to mimic TLS. I do not know the details, but I see some mentions in the sources of the clients.

**Comment by z991238** [comment] 2019-07-23 11:48
> 好消息，大家好 似乎TG将引入另一种机制，这将有助于避免审查和连接将模仿TLS。我不知道细节，但我在客户的来源中看到了一些提及。

Then I hope to study and release the GFW blockade against China as soon as possible. Because GFW's DPI capabilities are too strong. His border firewall is more effective than other countries

**Comment by z991238** [comment] 2019-08-21 02:12
> Good news, everyone. It seems that TG is going to introduce yet another mechanism which will help to avoid censorship and connection is going to mimic TLS. I do not know the details, but I see some mentions in the sources of the clients.

There are plans to support the new version of TLS confusion. Help us escape the review and hope to do an interactive one-click script for us to install. Thank you

**Comment by 9seconds** [comment] 2019-09-04 05:04
I close this ticket. Let's concentrate a discussion there: https://github.com/9seconds/mtg/issues/95

**Closed by 9seconds** 2019-09-04 05:04 UTC
