### ISSUE TITLE
OpenBSD (6.7) Support

### ISSUE THREAD

**Issue by FollowMeDown** [9seconds/mtg#148] opened 2020-06-10 02:04 UTC
Output from Test VM :
```
bastion$ mtg run -d c9de0de58ce51318b54c5e4333dd2dc7
{
  "ipv4": {
    "tg_url": "tg://proxy?port=3128&secret=c9de0de58ce51318b54c5e4333dd2dc7&server=209.250.250.193",
    "tme_url": "https://t.me/proxy?port=3128&secret=c9de0de58ce51318b54c5e4333dd2dc7&server=209.250.250.193",
    "tg_qrcode": "https://api.qrserver.com/v1/create-qr-code?data=tg%3A%2F%2Fproxy%3Fport%3D3128%26secret%3Dc9de0de58ce51318b54c5e4333dd2dc7%26server%3D209.250.250.193&format=svg&qzone=4",
    "tme_qrcode": "https://api.qrserver.com/v1/create-qr-code?data=tg%3A%2F%2Fproxy%3Fport%3D3128%26secret%3Dc9de0de58ce51318b54c5e4333dd2dc7%26server%3D209.250.250.193&format=svg&qzone=4"
  },
  "ipv6": {
    "tg_url": "tg://proxy?port=3128&secret=c9de0de58ce51318b54c5e4333dd2dc7&server=%3Cnil%3A",
    "tme_url": "https://t.me/proxy?port=3128&secret=c9de0de58ce51318b54c5e4333dd2dc7&server=%3Cnil%3A",
    "tg_qrcode": "https://api.qrserver.com/v1/create-qr-code?data=tg%3A%2F%2Fproxy%3Fport%3D3128%26secret%3Dc9de0de58ce51318b54c5e4333dd2dc7%26server%3D%253Cnil%253E&format=svg&qzone=4",
    "tme_qrcode": "https://api.qrserver.com/v1/create-qr-code?data=tg%3A%2F%2Fproxy%3Fport%3D3128%26secret%3Dc9de0de58ce51318b54c5e4333dd2dc7%26server%3D%253Cnil%253E&format=svg&qzone=4"
  },
  "secret_for_mtproxybot": "c9de0de58ce51318b54c5e4333dd2dc7"
}
{"level":"error","ts":1591753765.6807811,"logger":"proxy","msg":"Cannot initialize client TCP connection","connection_id":"ac1fcd983f1a4ded","error":"cannot set keep-alive period: set tcp 209.250.250.193:3128->82.236.232.233:41108: protocol not available"}

```

**Comment by FollowMeDown** [comment] 2020-06-11 23:03
{"level":"error","ts":1591753765.6807811,"logger":"proxy","msg":"Cannot initialize client TCP connection","connection_id":"ac1fcd983f1a4ded","error":"cannot set keep-alive period: set tcp 209.250.250.193:3128->82.236.232.233:41108: protocol not available"}

**Comment by 9seconds** [comment] 2020-06-15 09:51
Interesting, looks like a regression in [golang stdlib](https://golang.org/pkg/net/#TCPConn.SetKeepAlive). I'll take a look, thanks!

**Comment by 9seconds** [comment] 2020-06-15 09:52
No regression: it is documented in sources but not in, well, documentation: https://golang.org/src/net/tcpsockopt_openbsd.go

**Comment by 9seconds** [comment] 2020-08-10 12:20
Merged in master branch

**Closed by 9seconds** 2020-08-10 12:20 UTC
Labels: bug
