### ISSUE TITLE
panic nil ptr deref

### ISSUE THREAD

**Issue by kaey** [9seconds/mtg#194] opened 2021-05-16 14:37 UTC
```
scwm:~# go version -m /usr/sbin/mtg
/usr/sbin/mtg: go1.16.3
	path	github.com/9seconds/mtg/v2
	mod	github.com/9seconds/mtg/v2	v2.0.0	h1:wDQjXrMTzBSDIiwUYlYMn1z0Bzn0GVzsGfZpNlXnGMA=
	dep	github.com/OneOfOne/xxhash	v1.2.8	h1:31czK/TI9sNkxIKfaUfGlU47BAxQ0ztGgd9vPyqimf8=
	dep	github.com/alecthomas/kong	v0.2.16	h1:F232CiYSn54Tnl1sJGTeHmx4vJDNLVP2b9yCVMOQwHQ=
	dep	github.com/alecthomas/units	v0.0.0-20210208195552-ff826a37aa15	h1:AUNCr9CiJuwrRYS3XieqF+Z9B9gNxo/eANAJCF2eiN4=
	dep	github.com/babolivier/go-doh-client	v0.0.0-20201028162107-a76cff4cb8b6	h1:4NNbNM2Iq/k57qEu7WfL67UrbPq1uFWxW4qODCohi+0=
	dep	github.com/beorn7/perks	v1.0.1	h1:VlbKKnNfV8bJzeqoa4cOKqO6bYr3WgKZxO8Z16+hsOM=
	dep	github.com/cespare/xxhash/v2	v2.1.1	h1:6MnRN8NT7+YBpUIWxHtefFZOKTAPgGjpQSxqLNn0+qY=
	dep	github.com/golang/protobuf	v1.5.2	h1:ROPKBNFfQgOUMifHyP+KYbvpjbdoFNs+aK7DXlji0Tw=
	dep	github.com/kentik/patricia	v0.0.0-20201202224819-f9447a6e25f1	h1:D7qhJP3R49ZjUzpzKQ6B2H3lgejPs6DTO5gRomhhOpE=
	dep	github.com/libp2p/go-reuseport	v0.0.2	h1:XSG94b1FJfGA01BUrT82imejHQyTxO4jEWqheyCXYvU=
	dep	github.com/matttproud/golang_protobuf_extensions	v1.0.1	h1:4hp9jkHxhMHkqkrB3Ix0jegS5sx/RkqARlsWZ6pIwiU=
	dep	github.com/panjf2000/ants/v2	v2.4.4	h1:kebk2KSiXHGeiYS6b+w2RqNN5+IKoqlBNd7cuC7MvQI=
	dep	github.com/pelletier/go-toml	v1.9.0	h1:NOd0BRdOKpPf0SxkL3HxSQOG7rNh+4kl6PHcBPFs7Q0=
	dep	github.com/pkg/errors	v0.9.1	h1:FEBLx1zS214owpjy7qsBeixbURkuhQAwrK5UwLGTwt4=
	dep	github.com/prometheus/client_golang	v1.10.0	h1:/o0BDeWzLWXNZ+4q5gXltUvaMpJqckTa+jTNoB+z4cg=
	dep	github.com/prometheus/client_model	v0.2.0	h1:uq5h0d+GuxiXLJLNABMgp2qUWDPiLvgCzz2dUR+/W/M=
	dep	github.com/prometheus/common	v0.23.0	h1:GXWvPYuTUenIa+BhOq/x+L/QZzCqASkVRny5KTlPDGM=
	dep	github.com/prometheus/procfs	v0.6.0	h1:mxy4L2jP6qMonqmq+aTtOx1ifVWUgG/TAmntgbh3xv4=
	dep	github.com/rs/zerolog	v1.21.0	h1:Q3vdXlfLNT+OftyBHsU0Y445MD+8m8axjKgf2si0QcM=
	dep	github.com/smira/go-statsd	v1.3.2	h1:1EeuzxNZ/TD9apbTOFSM9nulqfcsQFmT4u1A2DREabI=
	dep	github.com/tylertreat/BoomFilters	v0.0.0-20210315201527-1a82519a3e43	h1:QEePdg0ty2r0t1+qwfZmQ4OOl/MB2UXIeJSpIZv56lg=
	dep	golang.org/x/crypto	v0.0.0-20210503195802-e9a32991a82e	h1:8foAy0aoO5GkqCvAEJ4VC4P3zksTg4X4aJCDpZzmgQI=
	dep	golang.org/x/net	v0.0.0-20210505024714-0287a6fb4125	h1:Ugb8sMTWuWRC3+sz5WeN/4kejDx9BvIwnPUiJBjJE+8=
	dep	golang.org/x/sys	v0.0.0-20210503173754-0981d6026fa6	h1:cdsMqa2nXzqlgs183pHxtvoVwU7CyzaCTAUOg94af4c=
	dep	google.golang.org/protobuf	v1.26.0	h1:bxAC2xTBsZGibn2RTntX0oH50xLsqy1OxA9tTL3p/lk=
```

```
scwm:~# cat /etc/mtg.conf
# /usr/sbin/mtg generate-secret --help
secret = "eeXXXXXXXX"
bind-to = "0.0.0.0:3130"

[stats.prometheus]
enabled = true
bind-to = "127.0.0.1:3131"
```

```
May 16 14:07:53 scwm user.notice mtg: panic: runtime error: invalid memory address or nil pointer dereference
May 16 14:07:53 scwm user.notice mtg: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x556b9e34c748]
May 16 14:07:53 scwm user.notice mtg: goroutine 38434 [running]:
May 16 14:07:53 scwm user.notice mtg: github.com/9seconds/mtg/v2/mtglib/internal/relay.(*Relay).transmit.func1(0x7fb0a549cfa8, 0xc00014c870, 0x7fb0a549cfd0, 0xc00014c900, 0xc0000a61d0, 0xc000076280)
May 16 14:07:53 scwm user.notice mtg: 	/root/local/aports/testing/mtg/src/go/pkg/mod/github.com/9seconds/mtg/v2@v2.0.0/mtglib/internal/relay/relay.go:75 +0x68
May 16 14:07:53 scwm user.notice mtg: github.com/9seconds/mtg/v2/mtglib/internal/relay.(*Relay).transmit(0xc000076280, 0x7fb0a549cfa8, 0xc00014c870, 0x7fb0a549cfd0, 0xc00014c900, 0xc0001ac000, 0x4000, 0x4000, 0x556b9e55567e, 0x4, ...)
May 16 14:07:53 scwm user.notice mtg: 	/root/local/aports/testing/mtg/src/go/pkg/mod/github.com/9seconds/mtg/v2@v2.0.0/mtglib/internal/relay/relay.go:92 +0x205
May 16 14:07:53 scwm user.notice mtg: created by github.com/9seconds/mtg/v2/mtglib/internal/relay.(*Relay).Process
May 16 14:07:53 scwm user.notice mtg: 	/root/local/aports/testing/mtg/src/go/pkg/mod/github.com/9seconds/mtg/v2@v2.0.0/mtglib/internal/relay/relay.go:55 +0x3b6
```

Stack trace is truncated because syslog is amazing piece of software. I can get a full one if you need.

**Comment by 9seconds** [comment] 2021-05-17 06:52
I expect this is a duplicate of https://github.com/9seconds/mtg/issues/188. Merged PR is https://github.com/9seconds/mtg/pull/189.

**Comment by 9seconds** [comment] 2021-05-17 06:55
I'm going to make a release today, mostly to include that fix

**Comment by 9seconds** [comment] 2021-05-17 13:34
A release has been made (v2.0.1). Please check and reopen if this problem happen again.

**Closed by 9seconds** 2021-05-17 13:34 UTC
