### ISSUE TITLE
Some media doesn't load

### ISSUE THREAD

**Issue by L11R** [9seconds/mtg#208] opened 2021-09-17 17:09 UTC
Without proxy everything works good. Logs are reporting connection to DC 203:
```mtg[974]: {"level":"warn","logger":"proxy","error":"cannot dial to Telegram: cannot dial to 203 dc: %!w(<nil>)","timestamp":1631898230591,"message":"cannot dial to telegram"}```

What could be wrong? 
I use simple-run mode and run it like that:
`mtg simple-run 0.0.0.0:443 eeSECRETHERE7777772e676f6f676c652d616e616c79746963732e636f6d -d`

**Comment by 9seconds** [comment] 2021-09-20 14:18
This error means that mtg was trying to establish a TCP connection to Telegram but failed. The most puzzling line here is `cannot dial to 203 dc`. I have no idea what is 203 DC. This is unknown DC. Telegram works with 5 DCs now.

Would you mind to share more details if this issue is still reproducible?

**Comment by L11R** [comment] 2021-09-20 15:42
@9seconds yep, I have also been surprised a bit. It was easy to reproduce at two of my VPSes, as I said I have just ran them by this command, scrolled some chats and started getting this error everywhere :(

**Comment by 3cky** [comment] 2021-09-22 14:34
It looks like only recently released Telegram clients are affected. Telegram Desktop 2.8.8 works just fine, but 3.0.1 doesn't display half of the stickers.

**Comment by 9seconds** [comment] 2021-09-22 15:34
This is quite weird. Telegram for OS X 8.1 (221723) Stable works perfectly. I also do not see any mentions about these DC in sources of Telegram Desktop. I gonna check with 3.0.1 later. If you can collect debug logs from mtg when you reproduce an issue and pass them to some pastebin, it would be useful.

**Comment by nmakhotkin** [comment] 2021-09-23 09:16
Hi @9seconds !
I have started to get those errors recently, probably, just right after client updates. Media does not load at all except for direct dialogs media (pictures/videos). So I grabbed logs in debug mode and here they are:

https://paste.openstack.org/show/809531/

Please take a look.

P.S. Neither my Android client nor Linux desktop client works.

**Comment by nmakhotkin** [comment] 2021-09-23 09:24
Also, I have tried TG desktop 2.9.14 - it does work as well.

**Comment by 9seconds** [comment] 2021-09-24 07:30
I've been trying to reproduce this issue with Telegram Desktop 3.1.0 for an hour. I've also connected with Telegram for iOS and Telegram for MacOS to the same proxy but haven't caught any issues with DC 203.

I've checked how mtproto_proxy works here: https://github.com/seriyps/mtproto_proxy/blob/2f2f2bb6b0470e1322cbd2c0c5eb0e870b99c67e/src/mtp_config.erl#L81-L102

```erlang
-spec get_netloc_safe(dc_id()) -> {dc_id(), netloc()}.
get_netloc_safe(DcId) ->
    case get_netloc(DcId) of
        {ok, Addr} -> {DcId, Addr};
        not_found ->
            [{?IDS_KEY, L}] = ets:lookup(?TAB, ?IDS_KEY),
            NewDcId = random_choice(L),
            %% Get random DC; it might return 0 and recurse aggain
            get_netloc_safe(NewDcId)
    end.

get_netloc(DcId) ->
    Key = ?IPS_KEY(DcId),
    case ets:lookup(?TAB, Key) of
        [] ->
            not_found;
        [{Key, [{_, _} = IpPort]}] ->
            {ok, IpPort};
        [{Key, L}] ->
            IpPort = random_choice(L),
            {ok, IpPort}
    end.
```

As a fallback it tries to connect to _any_ DC. In general it works because theoretically each DC is able to answer on RPC calls (latency will suffer though). I haven't implemented such fallback in mtg. Probably, it makes sense.

So, it will mitigate the issue. The reason though is something fishy in Telegram client. I've doublechecked how DC is parsed and every step seems correct :/

And again, I'm also unable to reproduce this issue. I do not have a linux box nearby so can't verify if there is any regression in Linux version of Telegram Desktop.

**Comment by L11R** [comment] 2021-09-24 08:22
In my case issue was at Windows PC. I will check master-version later.

**Comment by nmakhotkin** [comment] 2021-09-27 05:09
@9seconds Thanks for the fix! I will check it during a day and will post here the results.

**Comment by nmakhotkin** [comment] 2021-09-27 06:31
@9seconds Checked the new version on my server, works as expected. Thanks a lot! 
@L11R Could you please also check and close the issue?

**Comment by L11R** [comment] 2021-09-29 10:25
@nmakhotkin I've checked. In my case fix doesn't really helped. Many media still cannot be loaded for some reason or they are loading for minutes. Logs:
https://gist.github.com/L11R/c548419c2b56f252d788b97781d9bcb0

**Comment by 9seconds** [comment] 2021-10-02 12:24
This is really weird because it looks like Telegram closes a connection of this client, proxy is not responsible for that at all.

Help is required :/ I have no idea what is happening there and why.

**Comment by 9seconds** [comment] 2021-10-04 11:57
I've made a mentioned behavior configurable: https://github.com/9seconds/mtg/pull/216 A default for simple run is making a fallback. A default for configuration is rejecting a connection.

**Comment by L11R** [comment] 2021-12-05 15:52
@9seconds In my case media still doesn't load. Images load some time, but videos almost never. Currently I tried it with 2.1.4.
I guess the reason is that in my case it for some reason trying to connect to DC 203, mtg trying to fallback, but with no success.

**Comment by L11R** [comment] 2021-12-05 19:00
Well, after some digging I think I have found the problem. Telegram from some moment use relatively new CDN system: https://core.telegram.org/cdn

It presents us a new type of DC, CDN type, for example: https://github.com/tdlib/td/blob/master/td/telegram/net/DcOptions.h
The problem is that we can obtain their IP only as update: https://core.telegram.org/constructor/updateDcOptions

So for example user opens big channel with 100k+ subs and get this update with new CDN DC's. Then Telegram client gets updates about new messages and finds out that they are at CDN DC's. With updated DC list it now knows IP and connects.

The problems is that proxy has no idea about these CDN DC's and their IP. I don't know what we should do. I guess Telegram team should post CDN DC list somethere.

**Comment by 9seconds** [comment] 2021-12-06 08:07
It seems I should be able to get some results with [gotd](https://github.com/gotd/td), but this will require some funny actions so I'm going to prototype first and post results here once I'm done.

**Comment by 9seconds** [comment] 2021-12-08 11:15
Can't use gotd because even with correct results I need to embed api_key and api_hash into app. Do not want to do that. Also, proxies from getProxyConfig do not support direct connectivity. Moreover, I haven't found these 2xx there, only familiar -5..5

**Comment by 9seconds** [comment] 2021-12-10 12:19
So, after some research I want to make a following conclusion:

1. 203 DC is something that is coming from CDN and should not leak into mtproto proxy. So, this is definitely a bug in a client
2. I can't use gotd because it is required to have api key. mtg won't embed or require keys from Telegram
3. getProxyConfig from core.telegram.org returns only those proxies that support middle ones.

So far, I do not know how I could help. If one has any idea where to map these unknown DCs, this help is appreciated. I would try out to fallback to default DC for now which is 2. Thus, I close this issue.

**Closed by 9seconds** 2021-12-10 12:19 UTC
Labels: bug, help wanted
